"""Add Google OAuth fields to User model

Revision ID: 144c52807ceb
Revises: 
Create Date: 2025-12-26 23:24:05.949350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144c52807ceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('name')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
