"""Add historical data preservation fields to HealthData

Revision ID: d9d2dfc9f610
Revises: 144c52807ceb
Create Date: 2025-12-28 16:56:29.583660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d2dfc9f610'
down_revision = '144c52807ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_quality', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_user_provider', ['user_id', 'provider'], unique=False)
        batch_op.create_index('idx_user_provider_date', ['user_id', 'provider', 'date'], unique=False)
        batch_op.create_index('idx_user_provider_type', ['user_id', 'provider', 'data_type'], unique=False)
        batch_op.create_unique_constraint('unique_user_provider_type_date', ['user_id', 'provider', 'data_type', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_provider_type_date', type_='unique')
        batch_op.drop_index('idx_user_provider_type')
        batch_op.drop_index('idx_user_provider_date')
        batch_op.drop_index('idx_user_provider')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('data_quality')
        batch_op.drop_column('source_version')

    # ### end Alembic commands ###
